import type { Metadata } from "next";
import {  Quicksand } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import '@fortawesome/fontawesome-svg-core/styles.css';
import 'antd/dist/reset.css';
import SakuraEffectComponent from "@/components/sakura-foreground/SakuraEffectComponent";


const quicksand = Quicksand({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased`}
        style={{
          backgroundColor: "#C5ADC5",
          backgroundImage: "url('/backgroundSakura.webp')",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover", 
          backgroundPosition: "center",
        }}>
          <SakuraEffectComponent/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
