import type { Metadata } from "next";
import { Ramaraja, Quicksand, Reem_Kufi } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import '@fortawesome/fontawesome-svg-core/styles.css';
import 'antd/dist/reset.css';

// Font instances
const ramaraja = Ramaraja({ weight: "400", subsets: ["latin"] });
const quicksand = Quicksand({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });
const reemKufi = Reem_Kufi({ weight: ["400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
